base_config: configs/replica/replica.yaml

exp_name: replica/office2

# seeding: 42
enable_vis: False
hard_realtime: False

data_specs:
  data_path: '/mnt/dataset2/nice-slam/office2'
  max_depth: 10

tracker_specs:
  start_frame: 0
  end_frame: -1

tracker_specs:
  N_rays: 1024
  learning_rate: 0.01
  step_size: 0.05
  keyframe_freq: 10
  num_iterations: 30

mapper_specs:
  N_rays_each: 1024
  voxel_size: 0.2
  step_size: 0.05
  num_iterations: 15

criteria:
  rgb_weight: .5
  depth_weight: 1
  sdf_weight: 5000.0
  fs_weight: 10.0
  sdf_truncation: 0.05