log_dir: './logs'
decoder: nrgbd
dataset: replica

criteria:
  rgb_weight: .5
  depth_weight: 1
  sdf_weight: 5000.0
  fs_weight: 10.0
  sdf_truncation: 0.1

decoder_specs:
  depth: 2
  width: 128
  in_dim: 16
  skips: []
  embedder: none
  multires: 0

tracker_specs:
  N_rays: 1024
  learning_rate: 0.01
  start_frame: 0
  end_frame: -1
  step_size: 0.1
  show_imgs: False
  max_voxel_hit: 10
  keyframe_freq: 10
  num_iterations: 30

mapper_specs:
  N_rays_each: 1024
  num_embeddings: 20000
  use_local_coord: False
  voxel_size: 0.2
  step_size: 0.1
  window_size: 4
  num_iterations: 10
  max_voxel_hit: 10
  final_iter: 0
  mesh_res: 8
  overlap_th: 0.8

debug_args:
  verbose: false
  mesh_freq: 0
  render_freq: 50
  render_res: [640, 480]